package main;

public enum PlayerAction {
    BUILD_RESEARCH_STATION,
    TREAT_DISEASE,
    GIVE_KNOWLEDGE,
    TAKE_KNOWLEDGE,
    DISCOVER_CURE,
    DRIVE_FERRY,
    DIRECT_FLIGHT,
    CHARTER_FLIGHT,
    SHUTTLE_FLIGHT,
    VIEW_CARDS,
    PLAY_EVENT_CARD,
    ROLE_ACTION,
    SKIP_ACTION
}
